# Project name
name = "freight-kfc"

# Compatibility settings
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"

# Environment variables for production
[env.production]
NODE_ENV = "production"

# Development environment settings
[env.development]
NODE_ENV = "development"

# Enable logging and other observability features
[observability]
enabled = true