# Project name
name = "freight-kfc"

# Pages configuration
pages_build_output_dir = "./build/client"

# Compatibility settings
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Enable logging and other observability features
[observability]
enabled = true